#!/bin/bash
# Generate binarySchemata.inc from .bfbs files
# Usage: generate_binary_schemata.sh <bfbs_dir> <output_file> <xxd_path>
#
# Equivalent to Makefile:
#   cd logger/types/generated; for bfb in *.bfbs; do xxd -i $bfb > $(basename $bfb).h; done
#   cat logger/types/generated/*.bfbs.h > logger/generated/binarySchemata.inc

BFBS_DIR="$1"
OUTPUT_FILE="$2"
XXD="$3"

# Clear output file
echo "// Auto-generated binary schemata from .bfbs files" > "$OUTPUT_FILE"
echo "// Generated by generate_binary_schemata.sh" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Process each .bfbs file
cd "$BFBS_DIR"
for bfbs in *.bfbs; do
    if [ -f "$bfbs" ]; then
        # Generate xxd output and append to output file
        "$XXD" -i "$bfbs" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
    fi
done
