# Generates binarySchemata.inc from .bfbs files using xxd
# Usage: cmake -DBFBS_DIR=<dir> -DOUTPUT_FILE=<file> -DXXD=<xxd_path> -P GenerateBinarySchemata.cmake

if(NOT DEFINED BFBS_DIR)
    message(FATAL_ERROR "BFBS_DIR not defined")
endif()
if(NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "OUTPUT_FILE not defined")
endif()
if(NOT DEFINED XXD)
    message(FATAL_ERROR "XXD not defined")
endif()

# Get parent directory of output file and create if needed
get_filename_component(OUTPUT_DIR "${OUTPUT_FILE}" DIRECTORY)
file(MAKE_DIRECTORY "${OUTPUT_DIR}")

# Write header
file(WRITE "${OUTPUT_FILE}" "// Auto-generated binary schemata from .bfbs files\n")
file(APPEND "${OUTPUT_FILE}" "// Generated by GenerateBinarySchemata.cmake\n\n")

# Find all .bfbs files
file(GLOB BFBS_FILES "${BFBS_DIR}/*.bfbs")

foreach(bfbs ${BFBS_FILES})
    get_filename_component(bfbs_name "${bfbs}" NAME)
    message(STATUS "Processing ${bfbs_name}")
    
    # Run xxd -i on the file
    execute_process(
        COMMAND ${XXD} -i "${bfbs_name}"
        WORKING_DIRECTORY "${BFBS_DIR}"
        OUTPUT_VARIABLE XXD_OUTPUT
        RESULT_VARIABLE XXD_RESULT
    )
    
    if(NOT XXD_RESULT EQUAL 0)
        message(FATAL_ERROR "xxd failed on ${bfbs_name}")
    endif()
    
    file(APPEND "${OUTPUT_FILE}" "${XXD_OUTPUT}\n")
endforeach()

message(STATUS "Generated ${OUTPUT_FILE}")
